### ISSUE TITLE
runing the test in ubuntu 18.04

### ISSUE THREAD

**Issue by Ben-Sassi-Oussema** [abdou31/detect-covid19#2]
$ python test_covid19.py --input "normal" --output "aa"

Traceback (most recent call last):
  File "test_covid19.py", line 23, in <module>
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

**Comment by abdou31** [comment]
Hello @Ben-Sassi-Oussema, please try to check the path and the name of the input image :) .

**Comment by Ben-Sassi-Oussema** [comment]
i'm in the default path of the project and it's the same name of the image

**Comment by Ben-Sassi-Oussema** [comment]
![Capture du 2020-03-27 18-50-46](https://user-images.githubusercontent.com/16267611/77785192-221f4c00-705c-11ea-8312-ddd555dd247c.png)

**Comment by abdou31** [comment]
Put the image file format, I mean "jpg" , "jpeg" or "png" for e.g.

**Comment by Ben-Sassi-Oussema** [comment]
$python test_covid19.py --input "normal.jpeg" --output "out.jpeg"
you will have many other problems
Traceback (most recent call last):
  File "test_covid19.py", line 27, in <module>
    predIdxs = model.predict(img, batch_size=1)
  File "/home/sofia/.virtualenvs/dl4cv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 909, in predict
    use_multiprocessing=use_multiprocessing)
  File "/home/sofia/.virtualenvs/dl4cv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 462, in predict
    steps=steps, callbacks=callbacks, **kwargs)
  File "/home/sofia/.virtualenvs/dl4cv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 444, in _model_iteration
    total_epochs=1)
  File "/home/sofia/.virtualenvs/dl4cv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 123, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/home/sofia/.virtualenvs/dl4cv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 86, in execution_function
    distributed_function(input_fn))
  File "/home/sofia/.virtualenvs/dl4cv/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "/home/sofia/.virtualenvs/dl4cv/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 503, in _call
    self._initialize(args, kwds, add_initializers_to=initializer_map)
  File "/home/sofia/.virtualenvs/dl4cv/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 408, in _initialize
    *args, **kwds))
  File "/home/sofia/.virtualenvs/dl4cv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1848, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/sofia/.virtualenvs/dl4cv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2150, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/sofia/.virtualenvs/dl4cv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2041, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/sofia/.virtualenvs/dl4cv/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/sofia/.virtualenvs/dl4cv/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 358, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/sofia/.virtualenvs/dl4cv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 73, in distributed_function
    per_replica_function, args=(model, x, y, sample_weights))
  File "/home/sofia/.virtualenvs/dl4cv/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 760, in experimental_run_v2
    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
  File "/home/sofia/.virtualenvs/dl4cv/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 1787, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/home/sofia/.virtualenvs/dl4cv/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 2132, in _call_for_each_replica
    return fn(*args, **kwargs)
  File "/home/sofia/.virtualenvs/dl4cv/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 292, in wrapper
    return func(*args, **kwargs)
  File "/home/sofia/.virtualenvs/dl4cv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 162, in _predict_on_batch
    return predict_on_batch(model, x)
  File "/home/sofia/.virtualenvs/dl4cv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 370, in predict_on_batch
    return model(inputs)  # pylint: disable=not-callable
  File "/home/sofia/.virtualenvs/dl4cv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 847, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/home/sofia/.virtualenvs/dl4cv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 708, in call
    convert_kwargs_to_constants=base_layer_utils.call_context().saving)
  File "/home/sofia/.virtualenvs/dl4cv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 860, in _run_internal_graph
    output_tensors = layer(computed_tensors, **kwargs)
  File "/home/sofia/.virtualenvs/dl4cv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 847, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/home/sofia/.virtualenvs/dl4cv/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/convolutional.py", line 197, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/home/sofia/.virtualenvs/dl4cv/lib/python3.6/site-packages/tensorflow_core/python/ops/nn_ops.py", line 1134, in __call__
    return self.conv_op(inp, filter)
  File "/home/sofia/.virtualenvs/dl4cv/lib/python3.6/site-packages/tensorflow_core/python/ops/nn_ops.py", line 639, in __call__
    return self.call(inp, filter)
  File "/home/sofia/.virtualenvs/dl4cv/lib/python3.6/site-packages/tensorflow_core/python/ops/nn_ops.py", line 238, in __call__
    name=self.name)
  File "/home/sofia/.virtualenvs/dl4cv/lib/python3.6/site-packages/tensorflow_core/python/ops/nn_ops.py", line 2010, in conv2d
    name=name)
  File "/home/sofia/.virtualenvs/dl4cv/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_nn_ops.py", line 1071, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/home/sofia/.virtualenvs/dl4cv/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 631, in _apply_op_helper
    param_name=input_name)
  File "/home/sofia/.virtualenvs/dl4cv/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'input' has DataType uint8 not in list of allowed values: float16, bfloat16, float32, float64

**Comment by abdou31** [comment]
```python
img = tf.image.decode_jpeg()
img = tf.cast(image, tf.float32)
```

**Comment by Ben-Sassi-Oussema** [comment]
TypeError: decode_jpeg() missing 1 required positional argument: 'contents'

**Comment by Ben-Sassi-Oussema** [comment]
solution:
change with this line
img = cv2.imread(args["input"]).astype('float32')
